[build]
  publish = "pages"
  command = "# no build command needed"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Form submission handling
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Handle form submissions
[[redirects]]
  from = "/thank-you"
  to = "/pages/thank-you.html"
  status = 200

# Handle 404
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
